#!/bin/sh

base=$(dirname "$0")

mkdir -p "$base/data"
cd "$base/data" || exit 1

repos=$(gh repo list --json nameWithOwner -q '.[].nameWithOwner')

for repo in $repos; do
    pfx=$(gh repo view "$repo" --json id -q '.id' | shasum | cut -d' ' -f1)
    name=$(basename "$repo")-"$pfx"

    echo "Syncing: $name"

    if [ -d "$name" ]; then
        # Update existing repo
        (cd "$name" && git pull)
    else
        # Clone the repo
        gh repo clone "$repo" "$name"
    fi
done
